stages:
  - snapshot
  - release

.imgjob:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl

snapshot_arm32:
  extends: .imgjob
  stage: snapshot
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="armhf"
    - make build

snapshot_arm64:
  extends: .imgjob
  stage: snapshot
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="arm64"
    - make build

release_arm32:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - export TARGET="armhf"
    - make all

release_arm64:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - export TARGET="arm64"
    - make all
