stages:
  - build
  - release

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl
    - echo -n "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

dev_build:
  extends: .imgjob
  stage: build
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build

prod_build:
  extends: .imgjob
  stage: build
  only:
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - docker manifest create "${IMAGE}:${CE_TAG}" "${IMAGE}:${TARGET}"
    - docker manifest create "${IMAGE}:latest" "${IMAGE}:${TARGET}"
    - export TARGET="arm64"
    - make build
    - docker manifest annotate "${IMAGE}:${CE_TAG}" "${IMAGE}:${TARGET}"
    - docker manifest annotate "${IMAGE}:latest" "${IMAGE}:${TARGET}"

prod_release:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - docker manifest push "${IMAGE}:${CE_TAG}"
    - docker manifest push "${IMAGE}:latest"
