stages:
  - build
  - release

.imgjob:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl

dev_build:
  extends: .imgjob
  stage: build
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build

prod_build:
  extends: .imgjob
  stage: build
  only:
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build

prod_release:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - make publish
