stages:
  - release

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl

develop:
  extends: .imgjob
  stage: release
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build

production:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TAGLIST=$(echo -n "${TARGET}-${CE_TAG}" | tr -d [:space:])
    - export TARGET="arm64"
    - make build
    - export TAGLIST=$(echo -n "${TAGLIST} ${TARGET}-${CE_TAG}" | tr -d [:space:])
    - make push-manifest
