stages:
  - build
  - release

image: docker
services:
  - name: docker:dind
    command: ["--experimental"]
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: v0.11.2
  BUILDX_ARCHITECTURE: linux-arm64
before_script:
  - mkdir utils
  - apk add --no-cache make bash curl
  - mkdir -p ~/.docker/cli-plugins
  - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
  - chmod +x ~/.docker/cli-plugins/docker-buildx

arm32:
  stage: build
  tags:
  - docker
  - arm64
  only:
    - fork/master
    - develop    
  script:
    - export TARGET="arm32"
    - make build
    - export TAGLIST=$(make version)
    # build finished, image created
    - make push-manifest
    # released to dockerhub

arm64:
  stage: build
  tags:
  - docker
  - arm64
  only:
    - fork/master
    - develop
  script:
    - export TARGET="arm64"
    - make build
    - export TAGLIST=$(make version)
    # build finished, image created
    - make push-manifest
    # released to dockerhub
