stages:
  - snapshot
  - release

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl
    - echo -n "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

develop:
  extends: .imgjob
  stage: snapshot
  allow_failure: true
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build

production:
  extends: .imgjob
  stage: release
  only:
    - fork/master
  script:
    - export TARGET="armhf"
    - make build
    - export TARGET="arm64"
    - make build
    - make publish-manifest
