stages:
  - build
  - release

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
    BUILDX_VERSION: v0.5.1
  tags:
    - docker
    - arm64
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-arm64
    - chmod +x ~/.docker/cli-plugins/docker-buildx

build_arm32:
  extends: .imgjob
  stage: build
  only:
    - fork/master
  script:
    - export TARGET="arm"
    - make build
    - TAGLIST=$(make version)
    - echo "TAGLIST_ARM32=${TAGLIST}" >>versions.env
  artifacts:
    reports:
      dotenv: versions.env

build_arm64:
  extends: .imgjob
  stage: build
  only:
    - fork/master
  script:
    - export TARGET="arm64"
    - make build
    - TAGLIST=$(make version)
    - echo "TAGLIST_ARM64=${TAGLIST}" >>versions.env
  artifacts:
    reports:
      dotenv: versions.env

publish:
  extends: .imgjob
  stage: release
  depends: 
    - build_arm64
    - build_arm32
  only:
    - fork/master
  script:
    - export TAGLIST=${TAGLIST_ARM32}/${TAGLIST_ARM64}
    - make push-manifest
