stages:
  - snapshot
  - release

.imgjob:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash

build_test:
  extends: .imgjob
  stage: snapshot
  only:
    - branches
  except:
    - master
    - fork/master
  script:
    - make build
  allow_failure: true

build_release:
  extends: .imgjob
  stage: release
  only:
    - master
    - fork/master
  script:
    - make all
    - curl -X POST https://hooks.microbadger.com/images/ravermeister/armhf-gitlab/o9VyWZVOg4SYqB_BC57qn5Sm26Q=

