#!/bin/bash

set -e

if [ -f /etc/lsb-release ]; then
  source /etc/lsb-release
else
  source /etc/os-release
fi
source /RELEASE

# Install GitLab
/assets/download-package

dpkg -i /tmp/gitlab.deb
rm -f /tmp/gitlab.deb
rm -rf /var/lib/apt/lists/*

# Create sshd daemon
mkdir -p /opt/gitlab/sv/sshd/supervise /opt/gitlab/sv/sshd/log/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok /opt/gitlab/sv/sshd/log/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D -f /assets/sshd_config -e" > /opt/gitlab/sv/sshd/run
printf "#!/bin/sh\nexec svlogd -tt /var/log/gitlab/sshd" > /opt/gitlab/sv/sshd/log/run
chmod a+x /opt/gitlab/sv/sshd/run /opt/gitlab/sv/sshd/log/run

# Remove current gitlab.rb file
rm -f /etc/gitlab/gitlab.rb

# Patch omnibus package
sed -i "s/external_url 'GENERATED_EXTERNAL_URL'/# external_url 'GENERATED_EXTERNAL_URL'/" /opt/gitlab/etc/gitlab.rb.template
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/show_config.rb
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/config.rb

# Set install type to docker
echo 'gitlab-docker' > /opt/gitlab/embedded/service/gitlab-rails/INSTALLATION_TYPE

# Create groups (if they don't exist)
groupadd -f -g 998 git
groupadd -f -g 999 gitlab-www
groupadd -f -g 997 gitlab-redis
groupadd -f -g 996 gitlab-psql
groupadd -f -g 994 mattermost
groupadd -f -g 993 registry
groupadd -f -g 992 gitlab-prometheus
groupadd -f -g 991 gitlab-consul

# Create accounts (if they don't exist)
id -u git &>/dev/null || useradd -m -l -u 998 -g git -m -s /bin/sh -d /var/opt/gitlab git
id -u gitlab-www &>/dev/null || useradd -m -l -u 999 -g gitlab-www -m -s /bin/false -d /var/opt/gitlab/nginx gitlab-www
id -u gitlab-redis &>/dev/null || useradd -m -l -u 997 -g gitlab-redis -m -s /bin/false -d /var/opt/gitlab/redis gitlab-redis
id -u gitlab-psql &>/dev/null || useradd -m -l -u 996 -g gitlab-psql -m -s /bin/sh -d /var/opt/gitlab/postgresql gitlab-psql
id -u mattermost &>/dev/null || useradd -m -l -u 994 -g mattermost -m -s /bin/sh -d /var/opt/gitlab/mattermost mattermost
id -u registry &>/dev/null || useradd -m -l -u 993 -g registry -m -s /bin/sh -d /var/opt/gitlab/registry registry
id -u gitlab-prometheus &>/dev/null || useradd -m -l -u 992 -g gitlab-prometheus -m -s /bin/sh -d /var/opt/gitlab/prometheus gitlab-prometheus
id -u gitlab-consul &>/dev/null || useradd -m -l -u 991 -g gitlab-consul -m -s /bin/sh -d /var/opt/gitlab/consul gitlab-consul
