#!/bin/bash

set -e

is_minimum_version() {
  CUR_MAJOR_VER=$(printf "%s" "$1" | cut -d "." -f1)
  CUR_MINOR_VER=$(printf "%s" "$1" | cut -d "." -f2)
  CUR_PATCH_VER=$(printf "%s" "$1" | cut -d "." -f3)
  
  REQ_MAJOR_VER=$(printf "%s" "$2" | cut -d "." -f1)
  REQ_MINOR_VER=$(printf "%s" "$2" | cut -d "." -f2)
  REQ_PATCH_VER=$(printf "%s" "$2" | cut -d "." -f3)

  if [[ $CUR_MAJOR_VER -ge $REQ_MAJOR_VER \
      && $CUR_MINOR_VER -ge $REQ_MINOR_VER \
      && $CUR_PATCH_VER -ge $REQ_PATCH_VER \
  ]]; then
    return 0
  else
    return 1
  fi
}

# Install GitLab
if [ -f /etc/lsb-release ]; then
  source /etc/lsb-release
else
  source /etc/os-release
fi
source /RELEASE

/assets/download-package

dpkg -i /tmp/gitlab.deb
rm -f /tmp/gitlab.deb
rm -rf /var/lib/apt/lists/*

# Create sshd daemon
mkdir -p /opt/gitlab/sv/sshd/supervise /opt/gitlab/sv/sshd/log/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok /opt/gitlab/sv/sshd/log/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D -f /assets/sshd_config -e" > /opt/gitlab/sv/sshd/run
printf "#!/bin/sh\nexec svlogd -tt /var/log/gitlab/sshd" > /opt/gitlab/sv/sshd/log/run
chmod a+x /opt/gitlab/sv/sshd/run /opt/gitlab/sv/sshd/log/run

# Remove current gitlab.rb file
rm -f /etc/gitlab/gitlab.rb

# Patch omnibus package
sed -i "s/external_url 'GENERATED_EXTERNAL_URL'/# external_url 'GENERATED_EXTERNAL_URL'/" /opt/gitlab/etc/gitlab.rb.template
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/show_config.rb
# since gitlab 18.4.0 the file has moved from `gitlab` to `package` folder
if is_minimum_version "$SEM_VERSION" "18.4.0"; then
  sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/package/recipes/config.rb
else
  sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/config.rb
fi

# Set install type to docker
echo 'gitlab-docker' > /opt/gitlab/embedded/service/gitlab-rails/INSTALLATION_TYPE

# Create groups
groupadd -g 485 git
groupadd -g 486 gitlab-www
groupadd -g 487 gitlab-redis
groupadd -g 488 gitlab-psql
groupadd -g 489 mattermost
groupadd -g 490 registry
groupadd -g 491 gitlab-prometheus
groupadd -g 492 gitlab-consul

# Create accounts
useradd -m -l -u 485 -g git -m -s /bin/sh -d /var/opt/gitlab git
useradd -m -l -u 486 -g gitlab-www -m -s /bin/false -d /var/opt/gitlab/nginx gitlab-www
useradd -m -l -u 487 -g gitlab-redis -m -s /bin/false -d /var/opt/gitlab/redis gitlab-redis
useradd -m -l -u 488 -g gitlab-psql -m -s /bin/sh -d /var/opt/gitlab/postgresql gitlab-psql
useradd -m -l -u 489 -g mattermost -m -s /bin/sh -d /var/opt/gitlab/mattermost mattermost
useradd -m -l -u 490 -g registry -m -s /bin/sh -d /var/opt/gitlab/registry registry
useradd -m -l -u 491 -g gitlab-prometheus -m -s /bin/sh -d /var/opt/gitlab/prometheus gitlab-prometheus
useradd -m -l -u 492 -g gitlab-consul -m -s /bin/sh -d /var/opt/gitlab/consul gitlab-consul

