#!/bin/bash

set -eo pipefail

_docker(){
    docker "${@}"
}

build() {
    echo -e "\033[1mBuilding image: \033[32m${2}\033[0m"
    _docker build --no-cache --force-rm --compress --platform "${$1}" -t "${2}" -t "${3}" -f "${4}" "${5}"
}

# Set the version to install
if [ "$TARGET" = "arm64" ]; then
    RELEASE_FILE="docker/RELEASE_ARM64"
    PLATFORM="linux/arm64"
elif [ "$TARGET" = "armhf" ]; then
    RELEASE_FILE="docker/RELEASE_ARMHF"
    PLATFORM="linux/arm"
else
    echo "unkown architecture >$TARGET<" >&2
    exit 1
fi
sed -i -e 's/CE_VERSION/'"$CE_VERSION"'/g' "$RELEASE_FILE"

# Build the actual image
build "${PLATFORM}" "${IMAGE}:${TARGET}" "${IMAGE}:${CE_TAG}" "${DOCKERFILE}" docker/

#update tag variables
export TAGLIST=$(echo -n "$TAGLIST ${TARGET}-${CE_TAG}" | tr -d [:space:])
