#!/bin/bash

set -eo pipefail

_docker(){
    docker "${@}"
}

build() {
    echo -e "\033[1mBuilding image: \033[32m${1}\033[0m"
    _docker build --no-cache --force-rm --compress -t "${1}" -t "${2}" -f "${3}" "${4}"
}

# Set the version to install
sed -i -e 's/CE_VERSION/'"$CE_VERSION"'/g' docker/RELEASE

# Build the actual image
build "${IMAGE}:${TARGET}" "${IMAGE}:${CE_TAG}" "${DOCKERFILE}" docker/

#update tag variables
TAGLIST="$($TAGLIST ${TARGET}-${CE_TAG} | tr -d [:space:])"
