#!/bin/bash

set -eo pipefail

_docker(){
    docker "${@}"
}

push() {
    echo -e "\033[1mPushing manifest: \033[32m${1}\033[0m"
    _docker manifest push -p "${1}"
}

login() {
    echo "${2}" | awk '{print $0}' | _docker login --username "${1}" --password-stdin "${3}"
}

logout() {
    _docker logout "${1}"
}

if [[ -n "${CI_REGISTRY}" ]] && [[ -n "${CI_REGISTRY_USER}" ]]; then

    CI_REGISTRY_IMAGE="${CI_REGISTRY}/${CI_REGISTRY_USER}/${IMAGE_NAME}"
    FIRSTRUN=
    for TAG in $(echo -n "${TAGLIST}" | tr "/" " "); do        
        TARGET="$(echo -n "$TAG" | cut -d "-" -f1)"
        VERSION="$(echo -n "$TAG" | cut -d "-" -f2)"
        if [ "$FIRSTRUN" = "false" ]; then
            echo "add to existing manifest:latest"
            _docker manifest create -a "${CI_REGISTRY_IMAGE}:latest" "${IMAGE}:${TARGET}" "${IMAGE}:${VERSION}"

            echo "add to existing manifest:${VERSION}"
            _docker manifest create -a "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE}:${TARGET}" "${IMAGE}:${VERSION}"
        else
            echo "create new ${CI_REGISTRY_IMAGE}:latest ${IMAGE}:${TARGET} ${IMAGE}:${VERSION}"
            _docker manifest create "${CI_REGISTRY_IMAGE}:latest" "${IMAGE}:${TARGET}" "${IMAGE}:${VERSION}"

            echo "create new manifest:${VERSION}"
            _docker manifest create "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE}:${TARGET}" "${IMAGE}:${VERSION}"
            FIRSTRUN="false"
        fi
    done

    if [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]]; then
        login "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

        push "${CI_REGISTRY_IMAGE}:latest"
        for TAG in $(echo -n "${TAGLIST}" | tr "/" " "); do
            TARGET="$(echo -n "$TAG" | cut -d "-" -f1)"
            VERSION="$(echo -n "$TAG" | cut -d "-" -f2)"
            push "${CI_REGISTRY_IMAGE}:${VERSION}"
        done

        logout "${CI_REGISTRY}"
    fi
fi
